name: push to docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  testing:
    name: Testing API
    runs-on: ubuntu-latest
    container: golang:1.18
    services:
      mysql:
        image: mariadb:10.1
        env:
          MYSQL_ROOT_PASSWORD: testpw
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
    strategy:
      matrix:
        go: ["1.18"]
    steps:
      - uses: actions/checkout@v2
      - name: running test
        env:
          DBNAME: testdb
          DBHOST: mysql
          DBPORT: 3306
          DBUSER: root
          DBPASS: testpw
        run: |
          go mod tidy
          go test ./...

  build-container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: create env file
        env: 
          DB: ${{secrets.DB}}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }} 
          JWT_EXPIRED: ${{ secrets.JWT_EXPIRED }} 
          AZR_KEY: ${{secrets.AZR_KEY}}
          AZR_BLOB_ACC_NAME: ${{secrets.AZR_BLOB_ACC_NAME}}
          AZR_BLOB_CONTAINER: ${{secrets.AZR_BLOB_CONTAINER}}
          ROLE_ADMIN: ${{secrets.ROLE_ADMIN}}
        run: |
          touch .env
          echo DB=$DB >> .env
          echo DB_USER=$DB_USER >> .env
          echo DB_PASS=$DB_PASS >> .env
          echo DB_HOST=$DB_HOST >> .env
          echo DB_PORT=$DB_PORT >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo JWT_SECRET=$JWT_SECRET >> .env
          echo JWT_EXPIRED=$JWT_EXPIRED >> .env
          echo AZR_KEY=$AZR_KEY >> .env
          echo AZR_BLOB_ACC_NAME=$AZR_BLOB_ACC_NAME >> .env
          echo AZR_BLOB_CONTAINER=$AZR_BLOB_CONTAINER >> .env
          echo ROLE_ADMIN=$ROLE_ADMIN >> .env
      - name: login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}} #pakai akses token

      - name: build docker container
        run: docker build -t jiran03/mailku:v1 .

      - name: push docker container
        run: docker image push jiran03/mailku:v1
